name             'knife-windows'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures knife-windows'
long_description 'Installs/Configures knife-windows'
version          '0.1.0'
